### ISSUE TITLE
Split fetch projects epic into two

### ISSUE THREAD

**Issue by srishanbhattarai** [srishanbhattarai/Harbor#16]
* Currently `fetchAllProjects` epic does 2 tasks - fetch project list, and then for each project fetch its details. These need to be separate epics.

See the epic [here](https://github.com/srishanbhattarai/Harbor/blob/dev/src/epics/projectsEpic.js) and corresponding test [here](https://github.com/srishanbhattarai/Harbor/blob/dev/src/epics/projectsEpic.test.js).

**Comment by mesaugat** [comment]
Fixed in #24 - This issue should have closed automatically. Ah well!
