### ISSUE TITLE
Download button is not seen.

### ISSUE THREAD

**Issue by utshahs** [srishanbhattarai/Harbor#20]
Device name : S8
Android version: 7.0

**Comment by srishanbhattarai** [comment]
It works on my S8+ though. Not sure what the problem is, I'll check it out. Thanks 😄

**Comment by srishanbhattarai** [comment]
@utshahs Can you install the APK for the [v1.0.0-beta.02](https://github.com/srishanbhattarai/Harbor/releases/tag/v1.0.0-beta.02) release and let me know if it works fine now? Thanks!

**Comment by srishanbhattarai** [comment]
Fixed [here](https://github.com/srishanbhattarai/Harbor/releases/tag/v1.0.0-beta.03).
