### ISSUE TITLE
Push notification is not received after successfully uploading apk via Harbor CLI

### ISSUE THREAD

**Issue by laaptu** [srishanbhattarai/Harbor#23]
Not sure whether this issue is related to the app or the [Habor CLI](https://github.com/srishanbhattarai/Harbor-CLI), app is not receiving the push notification when apk is successfully uploaded using 

> harbor deploy

Details

- Harbor version: v1.0.0-beta.03-redeploy
- Harbor CLI version: 0.0.1
- Tested on: Nexus 6 (Android 7.1.1), Samsung S8 (Android 7.0) , Samsung S6 (Android 7.0), Huawei Mate 9 ( Android 7.0) , Google Pixel ( Android 8.0)

Right now manual refresh needs to be done to retrieve the newly uploaded apk.

Thank you.

**Comment by srishanbhattarai** [comment]
I believe I've exhausted my FCM quota. I don't have much expertise regarding the matter, but I do spot a bug in my app which causes leaking of quotas by sending FCM notifications to expired tokens. I don't think that'll solve the problem entirely but its a start. However, that belongs to the Harbor CLI repo. I will be closing this issue in this repo, and have opened a new one there.

Find the issue [here](https://github.com/srishanbhattarai/Harbor-CLI/issues/54).

Thank you.
