### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mesaugat** [srishanbhattarai/Harbor#25]
* Improve README
* Why, What and How?

<img width="227" alt="screen shot 2017-12-24 at 3 23 15 pm" src="https://user-images.githubusercontent.com/4240991/34325611-756a2254-e8be-11e7-8b26-619159de25e0.png">

**Comment by srishanbhattarai** [comment]
I am awful at these sort of things. I can tell when documentation is done right, but I can't seem to do it myself. 😭

**Comment by sriikanth** [comment]
@mesaugat is the issue still open?

**Comment by mesaugat** [comment]
@sriikanth Yes, the issue is still open. You can probably leave this issue to us.

**Comment by sriikanth** [comment]
@mesaugat okay.
